### ISSUE TITLE
Conception of the member model.

### ISSUE THREAD

**Issue by maximest-pierre** [ClubCedille/SiteCedille2.0#6]
The model must have these field:
* First Name
* Last Name
* Status
* Description

**Comment by samdidos** [comment]
Could be great to add a "department" field (ex : communication) and status could be replaced by "title" (ex. Event manager) or something like that. So those that are of Member department can add a personnalized title (like Python Charmer) if they want without disturbing their emplacement.

**Comment by maximest-pierre** [comment]
I might change description with bio and change the speciality to title (seems like a better fit actually).

**Comment by maximest-pierre** [comment]
There all fix. The pr to fix this is  #8
